#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 22 22:20:13 2019

@author: rushirajparmar
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset = pd.read_csv('/Users/rushirajparmar/Downloads/ML A-Z/Multiple_Linear_Regression/50_Startups.csv')
